---
abstract: 'Static analysis of Perl documents'
author:
  - 'Gregor Goldbach <glauschwuffel@nomaden.org>'
build_requires:
  Test::Deep: 0
  Test::Differences: 0
  Test::More: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Analysis-Static
requires:
  Carp: 0
  Config: 0
  Cwd: 0
  English: 0
  File::Next: 0
  FindBin: 0
  Getopt::Long: 0
  IO::Interactive: 0
  List::Util: 0
  Module::List: 0
  Module::Runtime: 0
  Moose: 0
  PPI: 0
  PPI::Cache: 0
  PPI::Node: 0
  Pod::Usage: 0
  Term::ANSIColor: 0
  Term::ProgressBar::Simple: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/glauschwuffel/Perl--Analysis--Static/issues
  homepage: https://github.com/glauschwuffel/Perl--Analysis--Static
  repository: git://github.com/glauschwuffel/Perl--Analysis--Static.git
version: 0.004
